# Generated by Django 5.2.11 on 2026-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_accepted', 'Order Accepted'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled'), ('order_status', 'Order Status Update'), ('new_subscription', 'New Subscription'), ('subscription_order', 'Daily Subscription Order'), ('subscription_paused', 'Subscription Paused'), ('subscription_resumed', 'Subscription Resumed'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_expired', 'Subscription Expired'), ('subscription_refund', 'Subscription Refund'), ('subscription_expiring', 'Subscription Expiring'), ('payment', 'Payment'), ('seller_approval', 'Seller Approval'), ('general', 'General')], max_length=25),
        ),
    ]
