# Generated by Django 5.2.11 on 2026-02-15 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('remaining_days', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skips_used', models.PositiveIntegerField(default=0)),
                ('max_skips', models.PositiveIntegerField(default=5)),
                ('pauses_used', models.PositiveIntegerField(default=0)),
                ('max_pauses', models.PositiveIntegerField(default=2)),
                ('is_auto_renew', models.BooleanField(default=False)),
                ('pause_start_date', models.DateField(blank=True, null=True)),
                ('pause_end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.subscriptionplan')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sellers.sellerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('confirmed', 'Confirmed'), ('skipped', 'Skipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='generated', max_length=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skip_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_refunded', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'skip_date')},
            },
        ),
    ]
