# Generated by Django 5.2.11 on 2026-02-18 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
        ('sellers', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_cea13a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['seller', 'status'], name='subscriptio_seller__f4d628_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_5ff966_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['-created_at'], name='subscriptio_created_cd574f_idx'),
        ),
    ]
